# TODO info about free area after kernel e.g. last kernel address and RAM_SIZE
export INFO_REG_OP=1
export REG_OP=2

export INFO_REG_A=3
export REG_A=4
export INFO_REG_B=5
export REG_B=6
export INFO_REG_C=7
export REG_C=8
export INFO_REG_D=9
export REG_D=10

export INFO_REG_RES=11
export REG_RES=12
export INFO_REG_BOOL_RES=13
export REG_BOOL_RES=14

export INFO_REG_ERROR=15
export REG_ERROR=16

export INFO_DISPLAY_BUFFER=17
export DISPLAY_BUFFER=18
export INFO_DISPLAY_COLOR=19
export DISPLAY_COLOR=20
export INFO_KEYBOARD_BUFFER=21
export KEYBOARD_BUFFER=22
export INFO_PROGRAM_COUNTER=23
export PROGRAM_COUNTER=24
export INFO_REG_STACK_PTR=25
export REG_STACK_PTR=26
export INFO_REG_STACK_PREV_PTR=27
export REG_STACK_PREV_PTR=28
export INFO_FREE_MEMORY_START=29
export FREE_MEMORY_START=30
export INFO_FREE_MEMORY_END=31
export FREE_MEMORY_END=32
export INFO_FREE_CHUNKS=33
export FREE_CHUNKS=34
